spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:mysql://localhost:3306/JobSearch
#    username: user
#    password: pass
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: false
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: validate
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
